import jsPDF from "jspdf";

export const downloadMedicalRecordPDF = (record) => {
  const doc = new jsPDF();

  // ===== Header =====
  doc.setFillColor(37, 99, 235); // blue
  doc.rect(0, 0, 210, 30, "F");
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(20);
  doc.setFont("helvetica", "bold");
  doc.text("SmartHealthCare System", 15, 18);
  doc.setFontSize(10);
  doc.text("Medical Record Report", 150, 18);

  // ===== Reset color =====
  doc.setTextColor(0, 0, 0);

  // ===== Patient Info =====
  doc.setFontSize(14);
  doc.setFont("helvetica", "bold");
  doc.text("Patient Information", 15, 45);
  doc.setDrawColor(37, 99, 235);
  doc.line(15, 47, 195, 47);

  doc.setFontSize(11);
  doc.setFont("helvetica", "normal");
  doc.text(`Patient Name : ${record.patient?.name || "N/A"}`, 15, 57);
  doc.text(`Blood Group  : ${record.patient?.bloodGroup || "N/A"}`, 15, 65);
  doc.text(`Phone        : ${record.patient?.phone || "N/A"}`, 15, 73);
  doc.text(`Date         : ${record.recordDate}`, 120, 57);

  // ===== Doctor Info =====
  doc.setFontSize(14);
  doc.setFont("helvetica", "bold");
  doc.text("Doctor Information", 15, 88);
  doc.line(15, 90, 195, 90);

  doc.setFontSize(11);
  doc.setFont("helvetica", "normal");
  doc.text(`Doctor Name      : Dr. ${record.doctor?.name || "N/A"}`, 15, 100);
  doc.text(`Specialization   : ${record.doctor?.specialization || "N/A"}`, 15, 108);
  doc.text(`Qualification    : ${record.doctor?.qualification || "N/A"}`, 15, 116);

  // ===== Diagnosis =====
  doc.setFontSize(14);
  doc.setFont("helvetica", "bold");
  doc.text("Diagnosis", 15, 131);
  doc.line(15, 133, 195, 133);

  doc.setFontSize(11);
  doc.setFont("helvetica", "normal");
  const diagLines = doc.splitTextToSize(record.diagnosis || "N/A", 175);
  doc.text(diagLines, 15, 143);

  // ===== Prescription =====
  doc.setFontSize(14);
  doc.setFont("helvetica", "bold");
  doc.text("Prescription", 15, 163);
  doc.line(15, 165, 195, 165);

  doc.setFontSize(11);
  doc.setFont("helvetica", "normal");
  const presLines = doc.splitTextToSize(record.prescription || "None", 175);
  doc.text(presLines, 15, 175);

  // ===== Notes =====
  doc.setFontSize(14);
  doc.setFont("helvetica", "bold");
  doc.text("Doctor Notes", 15, 195);
  doc.line(15, 197, 195, 197);

  doc.setFontSize(11);
  doc.setFont("helvetica", "normal");
  const noteLines = doc.splitTextToSize(record.notes || "No notes", 175);
  doc.text(noteLines, 15, 207);

  // ===== Footer =====
  doc.setFillColor(37, 99, 235);
  doc.rect(0, 280, 210, 17, "F");
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(9);
  doc.text("Generated by SmartHealthCare System", 15, 290);
  doc.text(`Date: ${new Date().toLocaleDateString()}`, 155, 290);

  // ===== Save =====
  doc.save(`Medical_Report_${record.patient?.name}_${record.recordDate}.pdf`);
};


export const downloadAppointmentPDF = (appointment) => {
  const doc = new jsPDF();

  // Header
  doc.setFillColor(37, 99, 235);
  doc.rect(0, 0, 210, 30, "F");
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(20);
  doc.setFont("helvetica", "bold");
  doc.text("SmartHealthCare System", 15, 18);
  doc.setFontSize(10);
  doc.text("Appointment Receipt", 152, 18);

  doc.setTextColor(0, 0, 0);

  // Appointment details
  doc.setFontSize(14);
  doc.setFont("helvetica", "bold");
  doc.text("Appointment Details", 15, 45);
  doc.setDrawColor(37, 99, 235);
  doc.line(15, 47, 195, 47);

  doc.setFontSize(12);
  doc.setFont("helvetica", "normal");
  doc.text(`Patient    : ${appointment.patient?.name || "N/A"}`, 15, 60);
  doc.text(`Doctor     : Dr. ${appointment.doctor?.name || "N/A"}`, 15, 72);
  doc.text(`Specialty  : ${appointment.doctor?.specialization || "N/A"}`, 15, 84);
  doc.text(`Date       : ${appointment.appointmentDate}`, 15, 96);
  doc.text(`Time       : ${appointment.appointmentTime}`, 15, 108);
  doc.text(`Status     : ${appointment.status}`, 15, 120);
  doc.text(`Symptoms   : ${appointment.symptoms || "N/A"}`, 15, 132);

  if (appointment.payment && appointment.payment.transactionId) {
    doc.setFont("helvetica", "bold");
    doc.setTextColor(79, 70, 229); // indigo
    doc.text(`Txn ID     : ${appointment.payment.transactionId}`, 15, 142);
    doc.setTextColor(0, 0, 0); // reset
    doc.setFont("helvetica", "normal");
  }

  // Fee box
  doc.setFillColor(239, 246, 255);
  doc.rect(15, 145, 180, 25, "F");
  doc.setFontSize(13);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(37, 99, 235);
  doc.text(`Consultation Fee: Rs. ${appointment.doctor?.consultationFee || "N/A"}`, 20, 161);

  // Footer
  doc.setFillColor(37, 99, 235);
  doc.rect(0, 280, 210, 17, "F");
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(9);
  doc.text("Generated by SmartHealthCare System", 15, 290);
  doc.text(`Date: ${new Date().toLocaleDateString()}`, 155, 290);

  doc.save(`Appointment_${appointment.doctor?.name}_${appointment.appointmentDate}.pdf`);
};